name: emma_flutter_sdk
description: EMMA SDK implementation for flutter. This package contains native bindings for our official SDK's. You can find more info at https://support.emma.io or https://www.emma.io
version: 1.4.0
homepage: https://www.emma.io

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.emma.emma_flutter_sdk
        pluginClass: EmmaFlutterSdkPlugin
      ios:
        pluginClass: EmmaFlutterSdkPlugin
